services:
  db:
    image: postgres:15
    container_name: ai-platform-db
    environment:
      POSTGRES_DB: ai_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  controltower-debug:
    build:
      context: ../ControlTower
      dockerfile: Dockerfile.debug
    container_name: ai-platform-controltower-debug
    environment:
      - ENVIRONMENT=development
      - DATABASE_TYPE=postgresql
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_platform
      - LOG_LEVEL=DEBUG
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8001
      - AUTH_SERVICE_URL=http://authservice:8000
    ports:
      - "8000:8000"  # ControlTower HTTP port
      - "5678:5678"  # Debug port for VS Code
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
