services:
  db:
    image: postgres:15
    container_name: ai-platform-db
    environment:
      POSTGRES_DB: ai_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network
    restart: unless-stopped

  controltower:
    build:
      context: ../ControlTower
      dockerfile: Dockerfile
    container_name: ai-platform-controltower
    environment:
      - ENVIRONMENT=dev
      - DATABASE_TYPE=postgresql
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_platform
      - SECRET_KEY=dev-secret-key-not-for-production
      - JWT_SECRET_KEY=dev-jwt-secret-key-not-for-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000,http://localhost:8001,http://localhost:8002
      - AGENTPLANE_BASE_URL=http://agentplane:8001
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  authservice:
    build:
      context: ../AuthService
      dockerfile: Dockerfile
    container_name: ai-platform-authservice
    environment:
      - ENVIRONMENT=dev
      - DATABASE_TYPE=postgresql
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_platform
      - OAUTH_REDIRECT_URI=http://localhost:8001/auth/callback
      - CONTROLTOWER_REDIRECT_URL=http://localhost:3000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000
      - COOKIE_SECURE=false
      - API_RELOAD=true
      - LOG_LEVEL=INFO
    ports:
      - "8001:8000"  # Map to different external port to avoid conflict
    networks:
      - app-network
    depends_on:
      - db
    restart: unless-stopped

  controlplaneux:
    build:
      context: ../ControlPlaneUX
      dockerfile: Dockerfile
      args:
        - BUILD_MODE=development
        - VITE_API_BASE_URL=http://localhost:8000
        - VITE_AUTH_SERVICE_URL=http://localhost:8001
        - VITE_ENVIRONMENT=development
        - VITE_DEBUG=true
    container_name: ai-platform-frontend
    ports:
      - "3000:80"  # Nginx serves on port 80 inside container
    networks:
      - app-network
    depends_on:
      - controltower
    restart: unless-stopped

  agentplane:
    build:
      context: ../AgentPlane
      dockerfile: Dockerfile
    container_name: ai-platform-agentplane
    environment:
      - ENVIRONMENT=dev
      - DATABASE_TYPE=postgresql
      - DATABASE_URL=postgresql://postgres:password@db:5432/ai_platform
      - SECRET_KEY=dev-secret-key-not-for-production
      - JWT_SECRET_KEY=dev-jwt-secret-key-not-for-production
      - CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://localhost:8000,http://localhost:8001,http://localhost:8002
      - CONTROLTOWER_BASE_URL=http://controltower:8000
      - AUTHSERVICE_BASE_URL=http://authservice:8000
    ports:
      - "8002:8001"  # Map to port 8002 externally to avoid conflicts
    networks:
      - app-network
    depends_on:
      - db
      - controltower
    restart: unless-stopped
    
volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
